server:
  host: "localhost"
  port: 8080

logger:
  level: "debug"

gin:
  mode: "release"

db_config:
  postgres:
    host: "localhost"
    port: 5433
    ssl_mode: "disable"
  max_open_conns: 5
  max_idle_conns: 10
  conn_max_lifetime: "100s"

retry_strategy:
  attempts: 3
  delay: "1s"
  backoffs: 2